#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Lint 규칙을 검사합니다."
if pnpm dlx lint-staged; then
  echo "✅ 모든 lint 규칙이 성공적으로 검사되었습니다."
  exit 0
else
  echo "❌ lint 규칙 검사에서 오류가 발생했습니다."
  exit 1
fi