name: "Build Test"

on: push

jobs:
  build:
    name: build test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Project
      uses: ./.github/actions/setup-project

    - name: Create .env file
      run: |
        jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}

    - name: Build Test
      run: pnpm build
      if: ${{ always() }}
    
    - name: Send Discord Message
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        embed-title: "Build Test"
        embed-description: "Build Test has been completed successfully."
