name: Build & Unit Test

on: push

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Project
      uses: ./.github/actions/setup-project

    - name: Create .env file
      run: |
        jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}

    - name: Build Test
      run: pnpm build
      if: ${{ always() }}

    - name: Run Unit Tests
      run: pnpm test
    
    - name: Send Discord Message
      uses: sarisia/actions-status-discord@v1.14.5
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
        status: ${{ job.status }}
        username: GitHub Actions
        title: ${{ github.workflow }}
