name: Build & Unit Test

on: push

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Project
      uses: ./.github/actions/setup-project

    - name: Create .env file
      run: |
        jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}

    - name: Build Test
      run: pnpm build
      if: ${{ always() }}

    - name: Set Status
      id: set_status
      run: |
        if [ "${{ job.status }}" == "success" ]; then
        echo "::set-output name=status_text::빌드 테스트가 완료되었어요."
        elif [ "${{ job.status }}" == "failure" ]; then
        echo "::set-output name=status_text::빌드 테스트가 실패했어요."
        else
        echo "::set-output name=status_text::빌드 테스트 상태를 확인하세요."
        fi

    - name: Run Unit Tests
      run: pnpm test
    
    - name: Send Discord Message
      uses: sarisia/actions-status-discord@v1.14.5
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
        status: ${{ job.status }}
        username: GitHub Actions
        title: ${{ steps.set_status.outputs.status_text }}
        url: "https://github.com/kdh379/sulview/actions/runs/${{ github.run_id }}"
