name: "notify-discord"

on:
  workflow_run:
    workflows: ["build-test"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord Message
      uses: sarisia/actions-status-discord@v1.14.5
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
        status: ${{ job.status }}
        username: GitHub Actions
        title: ${{ github.workflow }} - ${{ job.status }}