name: Notify Discord
on:
  workflow_call:
  workflow_run:
    workflows: [
      "Build Test",
      "Run Unit Tests"
    ]
    types:
      - completed
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord Message
      uses: tsickert/discord-webhook@v6.0.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        embed-title: ${{ github.event.workflow.name }}
        embed-url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        content: ${{ github.event.workflow_run.status }}
        embed-description: ${{ github.event.workflow_run.conclusion }}
        embed-color: 15430476