name: "Run Unit Tests"

on:
  workflow_run:
    workflows: ["build-test-on-every-push"]
    types:
      - completed

jobs:
  unit-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Project
      uses: ./.github/actions/setup-project

    - name: Run Unit Tests
      run: pnpm test