name: "Run Unit Tests"

on:
  workflow_run:
    workflows: ["build-test-on-every-push"]
    types:
      - completed

jobs:
  setup-env:
    uses: ./.github/workflows/setup-env.yml

  unit-test:
    needs: setup-env
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Project
      uses: ./.github/actions/setup-project

    - name: Download .env file
      uses: actions/download-artifact@v3
      with:
        name: env-file

    - name: Run Unit Tests
      run: pnpm test